
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 25 21:39:13 CST 2023
//----------------------------------------------------

package analyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 6;
  public static final int DIVIDE = 8;
  public static final int ERROR = 9;
  public static final int EOF = 0;
  public static final int PLUS = 5;
  public static final int EQ = 4;
  public static final int REAL = 3;
  public static final int error = 1;
  public static final int TIMES = 7;
  public static final int IDENTIFIER = 2;
}

